# Generated by Django 6.0.6 on 2026-10-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_categoria_nome_en_categoria_nome_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
